services:
  web:
    build: .
    container_name: csr_web
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: csr_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: csruser
      POSTGRES_PASSWORD: csrpass
      POSTGRES_DB: csrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: csr_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@csr.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data: